pull_requests:
  do_not_increment_build_number: true
skip_non_tags: true
image: Visual Studio 2019
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- cmd: >-
    dotnet --version
    dotnet restore ./src/DesafioZeDelivery.Api/DesafioZeDelivery.Api.csproj --verbosity m 
    dotnet restore ./src/DesafioZeDelivery.Core/DesafioZeDelivery.Core.csproj --verbosity m 
    dotnet restore ./src/DesafioZeDelivery.Abstraction/DesafioZeDelivery.Abstraction.csproj --verbosity m 
    dotnet restore ./src/DesafioZeDelivery.Domain/DesafioZeDelivery.Domain.csproj --verbosity m
    dotnet restore ./src/DesafioZeDelivery.Domain.Models/DesafioZeDelivery.Domain.Models.csproj --verbosity m
    dotnet restore ./src/DesafioZeDelivery.Infrastructure/DesafioZeDelivery.Infrastructure.csproj --verbosity m
    dotnet publish ./src/DesafioZeDelivery.Api/DesafioZeDelivery.Api.csproj
    dotnet publish ./src/DesafioZeDelivery.Core/DesafioZeDelivery.Core.csproj
    dotnet publish ./src/DesafioZeDelivery.Abstraction/DesafioZeDelivery.Abstraction.csproj
    dotnet publish ./src/DesafioZeDelivery.Domain/DesafioZeDelivery.Domain.csproj
    dotnet publish ./src/DesafioZeDelivery.Domain.Models/DesafioZeDelivery.Domain.Models.csproj
    dotnet publish ./src/DesafioZeDelivery.Infrastructure/DesafioZeDelivery.Infrastructure.csproj
test_script:
- cmd: dotnet test .\test\Mockaco.Tests\Mockaco.Tests.csproj