name: Continuous Integration

on: push

jobs:
  package:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Restore NuGet packages
        run: dotnet restore --verbosity normal
      - name: Build solution
        run: dotnet build --verbosity normal
      - name: Run tests
        run: dotnet test --no-build --verbosity normal
      - name: Publish
        run: dotnet publish -c Release --no-restore -o output/DesafioZeDelivery src/DesafioZeDelivery.Api/DesafioZeDelivery.Api.csproj
      - uses: actions/upload-artifact@master
        with:
          name: webpack artifacts
          path: output/DesafioZeDelivery
      
  publish:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: webpack artifacts
          path: output/DesafioZeDelivery
