name: Continuous Integration

on: push

env:
  Configuration: Release
  ContinuousIntegrationBuild: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:
  package:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    name: Run tests and create NuGet package
    outputs:
      version: ${{ steps.dotnet-pack.outputs.version }}
      nupkg-filename: ${{ steps.dotnet-pack.outputs.nupkg-filename }}
      release-body: ${{ steps.tag-message.outputs.release-notes }}
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Retrieve cached NuGet packages
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
      - name: Restore NuGet packages
        run: dotnet restore --verbosity normal
      - name: Build solution
        run: dotnet build --verbosity normal
      - name: Run tests
        run: dotnet test --no-build --verbosity normal
      - name: Publish
        run: dotnet publish -c Release --no-restore -o output/DesafioZeDelivery src/DesafioZeDelivery.Api/DesafioZeDelivery.Api.csproj
      - uses: actions/upload-artifact@master
        with:
          name: webpack artifacts
          path: output/DesafioZeDelivery
      
  publish:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: webpack artifacts
          path: output/DesafioZeDelivery
