name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Run Tests
      run: dotnet test .\test\DesafioZeDelivery.Test\DesafioZeDelivery.Test.csproj  
    - name: Build
      run: dotnet publish -c Release --no-restore -o output/DesafioZeDelivery src/DesafioZeDelivery.Api/DesafioZeDelivery.Api.csproj
    - uses: actions/upload-artifact@master
      with:
        name: webpack artifacts
        path: output/DesafioZeDelivery
        
  publish:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: webpack artifacts
          path: output/DesafioZeDelivery
